= FBTI Orchestration Service (prototype)

This service subscribes to an event queue. When an event is received, it checks whether the event is relevant for tax posting. If the answer is YES, then it calls a tax interface via the SAP Destination service.

== Prerequisites

* JDK 8+

== How to Build

Clone the code and then run:

[source,shell]
----
$ ./gradlew build
----

== How to Run

[source,shell]
----
$ ./gradlew bootRun
----

== Setup
=== Create Destination Service
[source,shell]
----
$ cf create-service destination lite destsrv
----
=== Create XSUAA Service
[source,shell]
----
$ cf create-service xsuaa application xsuaasrv
----
=== Create Connectivity Service
[source,shell]
----
$ cf create-service connectivity lite connsrv
----

== Integrate with S/4HANA Public Cloud System
If you have your target tax interface available in public internet, you could configure the interface endpoint using _HTTP Destination_ as described below.

If you have your tax interface published in S/4HANA Public Cloud system, you need to make sure the system is available in public internet. In a development landscape, it has to be a D-Lab or V-Lab system. Otherwise the system is only not reachable in the internet.

=== Create HTTP Destination
You need at least one configured http destination, otherwise there will be nothing to retrieve via the service.

To access the Destination Editor in the BTP cockpit, follow the steps in https://help.sap.com/docs/CP_CONNECTIVITY/cca91383641e40ffbe03bdc78f00f681/82ca377549c5421a8199013ea5f0facc.html[Access the Destinations Editor].

To create an HTTP destination from scratch, follow the steps in https://help.sap.com/docs/CP_CONNECTIVITY/cca91383641e40ffbe03bdc78f00f681/783fa1c418a244d0abb5f153e69ca4ce.html[Create HTTP Destination].

=== Configure Destination Name
Now change `my.destination.name` in application.yml

.application.yml
[source,yaml]
----
my:
  destination:
    name: <http-destination-name>
----

== Integrate with S/4HANA on-Premise Systems
If you have your target tax interface in S/4HANA OP system, you will need both _Connectivity_ + _Destination_ services on BTP. Plus you will need _SAP Cloud Connector_ in the same network of the target OP system.

In a development landscape, you must use the _https://shared-scc.wdf.sap.corp:8443[DLM Shared Cloud Connector]_. It won't be able to access the target system (e.g. ER9) if you install SAP Cloud Connector in your local computer.

After you logged-in the _DLM Shared Cloud Connector_, please configure your sub-account and _Cloud To On-Premise_ connection according to the configuration below.

.account_config.json
[source,json]
----
{
    "backends": [
        {
            "allowedClients": [],
            "authMode": "NONE",
            "backendType": "abapSys",
            "blacklistedUser": [],
            "cloudHost": "<virtual-host>",
            "cloudPort": "443",
            "description": "",
            "hostInHeader": "internal",
            "localHost": "<hostname>.wdf.sap.corp",
            "localPort": "44300",
            "protocol": "HTTPS",
            "resources": [
                {
                    "description": "",
                    "enabled": true,
                    "exactMatchOnly": false,
                    "fromScenarioOnly": false,
                    "path": "/",
                    "websocketUpgradeAllowed": false
                }
            ]
        }
    ]
}
----

And you need to configure the destination as following.

[source,properties]
----
#Password=<< Existing password/certificate removed on export >>
#
URL=http\://<virtual-host>\:443/sap/opu/odata/sap/ODATA_SERVICE
Name=<dev-system-id>
ProxyType=OnPremise
Type=HTTP
Authentication=BasicAuthentication
User=<your-abap-system-user>

----

=== Deploy to Cloud Foundry

Change the `application.name` in manifest.yml and then run

[source,shell]
----
$ cf push
----

=== Subscribe to the Event Queue using Webhook

==== Find Service Credentials
[source,shell]
----
$ cf service-key ems-fbti-orche skey
----

In the output, take a note of the below values.

[source,json]
----
{
 "management": [ ],
 "messaging": [
  { },
  { },
  {
   "broker": {
    "type": "saprestmgw"
   },
   "oa2": {
    "clientid": "<clientid>",
    "clientsecret": "<clientsecret>",
    "granttype": "client_credentials",
    "tokenendpoint": "<tokenendpoint>"
   },
   "protocol": [
    "httprest"
   ],
   "uri": "<uri>"
  }
 ],
}
----

==== Obtain JWT Token
[source,shell]
----
$ curl -X POST --location "https://simpletax.authentication.sap.hana.ondemand.com/oauth/token" \
    -H "Authorization: Basic <Base64 encoded clientid:clientsecret>" \
    -d "grant_type=client_credentials&response_type=token" \
  | yq -P -o json -
----

==== Create Event Subscription

Subscribe the deployed service to the fbti-staging queue, using webhook:

[source,shell]
----
$ curl -X POST --location "https://enterprise-messaging-pubsub.cfapps.sap.hana.ondemand.com/sap/ems/v1/events/subscriptions" \
    -H "Authorization: Bearer <JWT token>" \
    -H "Content-Type: application/json" \
    -d "{
          \"name\": \"fbti-orche-webhook\",
          \"qos\": \"AT_LEAST_ONCE\",
          \"events\": [
            {
              \"source\": \"/default/sap.fbti.orche/1\",
              \"type\": \"sap.fbti.orche.PostingRequest.Created.v1\"
            }
          ],
          \"webhookUrl\": \"<URL of this webhook app>\"
        }"
----

==== Verify Event Subscription

[source,shell]
----
$ curl -X GET \
    --location "https://enterprise-messaging-pubsub.cfapps.sap.hana.ondemand.com/sap/ems/v1/events/subscriptions/" \
    -H "Content-Type: application/cloudevents+json" \
    -H "Authorization: Bearer <JWT token>" \
 | yq -P -o json -
----

== How to Use
If you post an event to the https://github.wdf.sap.corp/I061761/fbti-staging-srv[Staging Service], the event will be forwared to the https://github.wdf.sap.corp/I061761/fbti-orchestration-srv[Orchestration Service]. And the API defined by HTTP destination will be called.

You may run script `send-event.py` to send event to the staging queue. Remember to change the variables before you use the script.
