---
spring:
  h2:
    console:
      enabled: off
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: off
logging:
  level:
    com.sap.financial.fbti: DEBUG
my:
  destination:
    name: <http-destination-name>